### ISSUE TITLE
Moving/Renaming files on /tmp/fuse_d over telnet

### ISSUE THREAD

**Issue by somacoder** [irungentoo/Xiaomi_Yi_4k_Camera#41]
I am attempting to rename files over telnet (Yi 4K) in the /tmp/fuse_d folder (sd card) via the mv command, but it doesn't seem to be possible at all. The entire prompt just hangs, and the system appears to lock up. Does anybody have experience with bypassing this limitation? Is it even possible?

Thanks!

**Comment by sukkamehu** [comment]
I tried to execute Linux commands long time in YI4K+ but gave up and got better camera - never again Chinese trash with bad official support.

Why don't they just use all great potential of this camera? It could be so good camera if it would be made to use some native GUI on Linux instead of that shit with all of its limits.

**Comment by somacoder** [comment]
Okay, figured it out. This feature is broken in later firmwares.

**Comment by MidoriYakumo** [comment]
filesystem command is only available in AmbaShell(i.e. autoexec.ash)
to invoke these actions via telnet it requires some rpc tricks, I did some test about it but it is quite long time ago

**Comment by somacoder** [comment]
Midori, could you share how you were able to access the AmbaShell over telnet? Thanks!
